In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import matplotlib.pyplot as plt

In [2]:
#Load data
data=pd.read_csv('/HD.csv')

# Separating the training set and test set
from sklearn.model_selection import train_test_split

X = data.drop('Heart Disease',axis=1)
y = data['Heart Disease']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=101)

In [3]:
# Normalization
norm_l = tf.keras.layers.Normalization(axis=-1)
norm_l.adapt(X_train)  # learns mean, variance # learns mean, variance
Xn_train = norm_l(X_train)
Xn_test = norm_l(X_test)

In [4]:
Xn_train.shape

TensorShape([189, 13])

In [5]:
y_train1=y_train[:,np.newaxis]

<ipython-input-5-f9f65187dd66>:1: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  y_train1=y_train[:,np.newaxis]


In [6]:
Xt = np.tile(Xn_train,(1000,1))
Yt= np.tile(y_train1,(1000,1))
print(Xt.shape, Yt.shape)

(189000, 13) (189000, 1)


In [7]:
y_train1.shape

(189, 1)

In [8]:
model = tf.keras.models.Sequential(
    [
        tf.keras.Input(shape=(13,)),    # specify input size (optional)
        Dense(8, activation='linear'),
        #Dense(8, activation='sigmoid'),
        Dense(4, activation='linear'),
        Dense(1,activation='sigmoid')
    ]
)

In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 112       
                                                                 
 dense_1 (Dense)             (None, 4)                 36        
                                                                 
 dense_2 (Dense)             (None, 1)                 5         
                                                                 
Total params: 153 (612.00 Byte)
Trainable params: 153 (612.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [10]:
[layer1, layer2, layer3] = model.layers

In [11]:
#### Examine Weights shapes
W1,b1 = layer1.get_weights()
W2,b2 = layer2.get_weights()
W3,b3 = layer3.get_weights()
#W4,b4 = layer4.get_weights()
print(f"W1 shape = {W1.shape}, b1 shape = {b1.shape}")
print(f"W2 shape = {W2.shape}, b2 shape = {b2.shape}")
print(f"W3 shape = {W3.shape}, b3 shape = {b3.shape}")
#print(f"W4 shape = {W4.shape}, b4 shape = {b4.shape}")

W1 shape = (13, 8), b1 shape = (8,)
W2 shape = (8, 4), b2 shape = (4,)
W3 shape = (4, 1), b3 shape = (1,)


In [12]:
model.compile(
    loss = tf.keras.losses.BinaryCrossentropy(),
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.01),
    metrics=['accuracy']
)



In [13]:
model.fit(
    Xt,Yt,
    epochs=10,
)

Epoch 1/10
5907/5907 [==============================] - 11s 2ms/step - loss: 0.3130 - accuracy: 0.8651
Epoch 2/10
5907/5907 [==============================] - 10s 2ms/step - loss: 0.3108 - accuracy: 0.8642
Epoch 3/10
5907/5907 [==============================] - 7s 1ms/step - loss: 0.3103 - accuracy: 0.8645
Epoch 4/10
5907/5907 [==============================] - 7s 1ms/step - loss: 0.3102 - accuracy: 0.8629
Epoch 5/10
5907/5907 [==============================] - 7s 1ms/step - loss: 0.3100 - accuracy: 0.8634
Epoch 6/10
5907/5907 [==============================] - 7s 1ms/step - loss: 0.3100 - accuracy: 0.8643
Epoch 7/10
5907/5907 [==============================] - 7s 1ms/step - loss: 0.3100 - accuracy: 0.8629
Epoch 8/10
5907/5907 [==============================] - 6s 1ms/step - loss: 0.3100 - accuracy: 0.8627
Epoch 9/10
5907/5907 [==============================] - 7s 1ms/step - loss: 0.3101 - accuracy: 0.8620
Epoch 10/10
5907/5907 [==============================] - 7s 1ms/step - loss: 0.3

In [14]:
W1, b1 = model.get_layer("dense").get_weights()
W2, b2 = model.get_layer("dense_1").get_weights()
W3, b3 = model.get_layer("dense_2").get_weights()
#W4, b4 = model.get_layer("dense_3").get_weights()
print("W1:\n", W1, "\nb1:", b1)
print("W2:\n", W2, "\nb2:", b2)
print("W3:\n", W3, "\nb3:", b3)
#print("W4:\n", W4, "\nb4:", b4)

W1:
 [[ 1.22791201e-01 -1.15616821e-01 -1.07290022e-01  4.81712669e-01
  -1.57024801e-01  4.51868214e-02  9.09499358e-04 -2.23984700e-02]
 [ 1.11237362e-01 -3.29512179e-01 -2.02296615e-01 -2.43122673e+00
   2.15333834e-01 -2.79387027e-01 -2.10517824e-01 -2.68527776e-01]
 [-7.13112354e-02  1.12203278e-01 -1.87567711e-01 -2.36795020e+00
   8.03626105e-02  2.46010572e-02 -3.92497666e-02 -1.12232082e-01]
 [-2.43668735e-01 -2.53490090e-01  6.60894886e-02 -2.49817300e+00
  -5.11742830e-02 -1.61282897e-01 -7.26155266e-02 -7.12543493e-03]
 [-9.35353991e-03  1.56083688e-01  3.15920785e-02 -1.01168215e+00
   2.66083665e-02  3.53680737e-02  1.22702919e-01 -1.24637790e-01]
 [-7.25005418e-02  2.11089820e-01  1.51997700e-01  1.33106887e+00
  -6.47428259e-02  2.22778395e-01 -5.91812506e-02 -3.13237995e-01]
 [ 1.01067320e-01 -1.32260785e-01  2.56445199e-01 -1.28383577e+00
  -4.30809781e-02  1.15009554e-01 -1.42830104e-01  3.99090722e-02]
 [ 2.42950231e-01  2.16956660e-01 -2.14471117e-01  1.84725249e+0

In [15]:
predictions = model.predict(Xn_test)
print("predictions = \n", predictions)

3/3 [==============================] - 0s 3ms/step
predictions = 
 [[0.08507314]
 [0.50735825]
 [0.57058996]
 [0.10421134]
 [0.69213206]
 [0.48740438]
 [0.96564674]
 [0.03317716]
 [0.15774941]
 [0.5062563 ]
 [0.582735  ]
 [0.29137218]
 [0.10313156]
 [0.878701  ]
 [0.03674812]
 [0.9956887 ]
 [0.42747065]
 [0.9642439 ]
 [0.02028359]
 [0.8306916 ]
 [0.2306711 ]
 [0.96724325]
 [0.87108487]
 [0.05175461]
 [0.02348582]
 [0.84679186]
 [0.01210277]
 [0.10370755]
 [0.96297693]
 [0.11113969]
 [0.00570288]
 [0.9920175 ]
 [0.05087341]
 [0.9620804 ]
 [0.53260636]
 [0.03103052]
 [0.02708602]
 [0.01113757]
 [0.9978184 ]
 [0.51384914]
 [0.99864495]
 [0.59724593]
 [0.04670899]
 [0.9032116 ]
 [0.02501437]
 [0.98763657]
 [0.6761641 ]
 [0.12166962]
 [0.05195672]
 [0.99958813]
 [0.99467254]
 [0.00848676]
 [0.98770416]
 [0.877729  ]
 [0.16607665]
 [0.05773962]
 [0.04297833]
 [0.9310989 ]
 [0.08843779]
 [0.2308521 ]
 [0.10233359]
 [0.9794578 ]
 [0.15749176]
 [0.37663782]
 [0.88234836]
 [0.30628496]
 [0.98949

In [16]:
X_test

Age  Sex  Chest pain type     BP  Cholesterol  FBS over 120  \
239  48.0  1.0              2.0  110.0   229.000000           0.0   
32   60.0  1.0              3.0  140.0   185.000000           0.0   
212  66.0  1.0              4.0  112.0   212.000000           0.0   
13   64.0  1.0              1.0  110.0   251.155102           0.0   
253  56.0  1.0              3.0  130.0   256.000000           1.0   
..    ...  ...              ...    ...          ...           ...   
262  43.0  1.0              4.0  115.0   303.000000           0.0   
104  57.0  1.0              3.0  128.0   229.000000           0.0   
181  55.0  0.0              2.0  135.0   251.155102           0.0   
25   37.0  1.0              3.0  130.0   251.155102           0.0   
150  51.0  1.0              3.0   94.0   227.000000           0.0   

     EKG results  Max HR  Exercise angina  ST depression  Slope of ST  \
239          0.0   168.0              0.0            1.0          3.0   
32           2.0   155.0              0.0            3.0          2.0   
212          2.0   132.0              1.0            0.1          1.0   
13           2.0   144.0              1.0            1.8          2.0   
253          2.0   142.0              1.0            0.6          2.0   
..           ...     ...              ...            ...          ...   
262          0.0   181.0              0.0            1.2          2.0   
104          2.0   150.0              0.0            0.4          2.0   
181          2.0   161.0              0.0            1.4          2.0   
25           0.0   187.0              0.0            3.5          3.0   
150          0.0   154.0              1.0            0.0          1.0   

     Number of vessels fluro  Thallium  
239                      0.0       7.0  
32                       0.0       3.0  
212                      1.0       3.0  
13                       0.0       3.0  
253                      1.0       6.0  
..                       ...       ...  
262                      0.0       3.0  
104                      1.0       7.0  
181                      0.0       3.0  
25                       0.0       3.0  
150                      1.0       7.0  

[81 rows x 13 columns]

In [17]:
yhat = np.zeros_like(predictions)
for i in range(len(predictions)):
    if predictions[i] >= 0.5:
        yhat[i] = 1
    else:
        yhat[i] = 0
print(f"decisions = \n{yhat}")

decisions = 
[[0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]]


In [18]:
y_test

239    1.0
32     1.0
212    1.0
13     0.0
253    1.0
      ... 
262    0.0
104    1.0
181    0.0
25     0.0
150    0.0
Name: Heart Disease, Length: 81, dtype: float64

In [19]:
 probability_model = tf.keras.Sequential([
   model,
   tf.keras.layers.Softmax()
 ])

In [20]:
 probability_model(Xn_test)


<tf.Tensor: shape=(81, 1), dtype=float32, numpy=
array([[0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
       [0.99999994],
      

In [21]:
model.evaluate(Xn_test,y_test,verbose=2)

3/3 - 0s - loss: 0.4440 - accuracy: 0.8395 - 107ms/epoch - 36ms/step


[0.44397297501564026, 0.8395061492919922]

In [22]:
model.evaluate(X_test,y_test,verbose=2)

3/3 - 0s - loss: 50.6126 - accuracy: 0.4198 - 86ms/epoch - 29ms/step


[50.612640380859375, 0.4197530746459961]

layer 9 8 4 1 accu cao, phai xai all sigmoid
xai softmax bi overfitting
9 4 1 cung bị ovèitting

xai sigmoid truong hop nào cũng bị underfitting

9 4 1 all sigmoid [2.762671947479248, 0.7407407164573669]
de khong bi overfitting xai relu
8 4 1 relu relu sigmoid

```
# This is formatted as code
```

